"""General ``G_N x SO(3)`` / ``E(3)`` representation tools."""

from importlib import import_module

__version__ = "0.1.0"


_LAZY_MODULES = (
    "ye3t.api",
    "ye3t.representations",
    "ye3t.fermion_wedge",
    "ye3t.core.couplings",
)

_ALIASES = {
    "fermion_wedge_physical_output_type": ("ye3t.fermion_wedge", "physical_output_type"),
    "fermion_wedge_sign_partition": ("ye3t.fermion_wedge", "sign_partition"),
    "IrrepTerm": ("ye3t.core.irreps", "IrrepTerm"),
}


def __getattr__(name):
    alias = _ALIASES.get(name)
    if alias is not None:
        module = import_module(alias[0])
        value = getattr(module, alias[1])
        globals()[name] = value
        return value
    for module_name in _LAZY_MODULES:
        module = import_module(module_name)
        if hasattr(module, name):
            value = getattr(module, name)
            globals()[name] = value
            return value
    raise AttributeError(name)


__all__ = [
    "AngularIrrep",
    "FermionWedgeSectorSpec",
    "CoupledIrrepLabel",
    "E3OperatorIR",
    "ExactFeatureSpace",
    "ExactProductColumnDescriptor",
    "ExactProductExpansionEngine",
    "ExactSchedule",
    "FixedContentDecomposition",
    "FixedContentModule",
    "FixedContentMultiplicityLabel",
    "FixedContentSector",
    "FixedContentSpec",
    "FlatScheduleMetadata",
    "DEFAULT_LOCAL_COEFFICIENT_BENCHMARK_TARGET_SECONDS",
    "YE3TAPI",
    "YE3TChannelReduction",
    "YE3TSymbolicSummary",
    "GeneralizedSectorData",
    "IndependentDecomposableProductSubspace",
    "IrrepTerm",
    "MaterializationDecision",
    "MaterializationPlan",
    "Partition",
    "PartitionCentralizerValidationReport",
    "PermutationIrrep",
    "PermutationSubgroup",
    "PermutationSubgroupFactor",
    "PrimitiveQuotientSummary",
    "RealFactorizedCoefficientSchedule",
    "ScheduleCostModel",
    "ScheduleOptions",
    "AngularCGMap",
    "BalancedYE3TMessageStateSpec",
    "BalancedTreeCompilation",
    "BalancedYE3TMessagePassingReferenceEvaluation",
    "BalancedYE3TMessagePassingSchedule",
    "BalancedYE3TMessageSectorReferenceEvaluation",
    "BalancedYE3TMessageSectorSchedule",
    "BalancedYE3TMessageStateReferenceView",
    "BalancedYE3TMessageStateTensorContainer",
    "BalancedYE3TCoupledSectorPathRecoupler",
    "BalancedYE3TChannelLinearReferenceMessageLayer",
    "BalancedYE3TPathCoupledReferenceMessageUpdateLayer",
    "BalancedYE3TReferenceMessageLayer",
    "BalancedYE3TReferenceLinearReadoutEvaluation",
    "BalancedYE3TRecursivePairProductReferenceStackEvaluation",
    "BalancedYE3TRecursivePairProductReferenceStackLayer",
    "BalancedYE3TRankCouplingPolicy",
    "CompileBalancedYE3TCoupledSectorPathRecoupler",
    "CompileSameRankKroneckerRuntimeTables",
    "SameRankKroneckerIntertwinerReferenceEvaluation",
    "SameRankKroneckerIntertwinerReference",
    "SameRankKroneckerMultiplicity",
    "SameRankKroneckerReference",
    "SameRankKroneckerRuntimeTableBundle",
    "evaluate_same_rank_kronecker_intertwiner_reference_torch",
    "ApplyBalancedYE3TChannelLinearUpdate",
    "ApplyBalancedYE3TChannelLinearReferenceMessageLayer",
    "ApplyBalancedYE3TCoupledSectorPathAngularCoupledReferenceMessageUpdate",
    "ApplyBalancedYE3TCoupledSectorPathAngularProductMerge",
    "ApplyBalancedYE3TCoupledSectorPathCoupledReferenceMessageUpdate",
    "ApplyBalancedYE3TCoupledSectorPathProductMerge",
    "ApplyBalancedYE3TMessageSumAggregation",
    "ApplyBalancedYE3TPairProductMerge",
    "ApplyBalancedYE3TPathCoupledReferenceMessageUpdate",
    "ApplyBalancedYE3TPairProductReferenceMessageLayer",
    "ApplyBalancedYE3TRecursivePairProductReferenceStack",
    "ApplyBalancedYE3TReferenceLinearReadout",
    "ApplyBalancedYE3TReferenceMessageLayer",
    "ApplyBalancedYE3TSectorwiseScalarUpdate",
    "ValidateBalancedYE3TAtomicScalarReferenceReadout",
    "ValidateBalancedYE3TAtomicScalarReferenceReadoutHiddenJacobian",
    "ValidateBalancedYE3TFermionExchangeReferenceReadout",
    "CompileBalancedTree",
    "CompileBalancedYE3TMessagePassingSchedule",
    "EvaluateBalancedYE3TMessagePassingScheduleReference",
    "PackageBalancedYE3TMessagePassingReferenceState",
    "CompileExteriorPower",
    "CompileGlobalYE3TCouplerFamily",
    "CompileGlobalYE3TCouplers",
    "CompileGlobalYE3TCouplersCached",
    "AssembleJointYoungE3Coupler",
    "assemble_joint_young_e3_coupler",
    "CompileYE3TCouplers",
    "CompileIndependentACE",
    "ExteriorPowerSignTable",
    "ExteriorSignReferenceEvaluation",
    "GlobalCouplerFamilyReferenceEvaluation",
    "GlobalCouplerReferenceEvaluation",
    "GlobalYE3TCouplerFamily",
    "GlobalYE3TLabel",
    "JointYoungE3Coupler",
    "KappaBlockLabel",
    "RANK_COUPLING_MODES",
    "RepeatedContentImageMap",
    "READOUT_AGGREGATIONS",
    "STRICT_RUNTIME_STATUSES",
    "TensorProductReduction",
    "TorchRealFactorizedCoefficientSchedule",
    "YE3TBackendPlan",
    "YE3TCouplerCertificate",
    "YE3TReadoutSpec",
    "YE3TRotationTarget",
    "YE3TSpec",
    "YoungInductionCoupler",
    "YoungSubductionMap",
    "LittlewoodRichardsonChainLabel",
    "LittlewoodRichardsonTableau",
    "ReducedMultiplicityInnerProduct",
    "TrivialSymmetricSubductionCoefficients",
    "YoungInducedBasisEntry",
    "YoungNaryInducedBasisEntry",
    "YoungOrthogonalNaryCoherenceReport",
    "YoungOrthogonalNaryCoherenceSuiteReport",
    "YoungOrthogonalNarySubductionTensor",
    "YoungOrthogonalNaryValidationReport",
    "YoungOrthogonalCoupledVector",
    "YoungOrthogonalCouplingTensor",
    "YoungOrthogonalValidationReport",
    "YoungOrthogonalValidationSuiteReport",
    "YoungSubgroupSpechtCoupling",
    "YoungSubgroupSpechtCouplingSpec",
    "YoungAnalyticalSectorCatalog",
    "YoungAnalyticalSectorCatalogValidation",
    "YoungAnalyticalSectorRecord",
    "YoungProductPath",
    "YoungResolvedPrimitiveQuotient",
    "YoungSectorCounts",
    "YoungSpechtBasisConstructionPlan",
    "YoungSpechtBasisConstructionPlanValidation",
    "YoungSpechtConstructionRecord",
    "YoungYamanouchiCGTreeSchedule",
    "YoungYamanouchiCGTreeScheduleValidation",
    "YoungYamanouchiCGRuntimeCoefficient",
    "YoungYamanouchiCGRuntimeSchedule",
    "YoungYamanouchiCGRuntimeScheduleValidation",
    "all_young_character_irreps_for_pattern",
    "analytical_young_e3_sector_catalog",
    "apply_exterior_sign_vector_torch",
    "apply_sparse_coefficient_table_torch",
    "build_exact_schedule",
    "build_flat_schedule_metadata",
    "build_materialization_plan",
    "build_invariant_sector_labels",
    "build_cached_young_subgroup_specht_coupling",
    "build_trivial_target_young_subgroup_specht_coupling",
    "build_young_subgroup_specht_coupling",
    "build_operator_ir",
    "build_operator_irs",
    "cg_tensor_product_reduction",
    "compile_global_ye3t_coupler_family",
    "compile_global_ye3t_couplers",
    "compile_permutation_coupler",
    "compile_rotation_coupler",
    "compile_same_rank_kronecker",
    "compile_ye3t_couplers",
    "compile_young_specht_basis_schedule",
    "compile_young_yamanouchi_pair_cg_runtime_schedule",
    "dusson_barthelemy_trivial_sector_counts",
    "enumerate_young_subgroup_specht_couplings",
    "enumerate_rank_labels",
    "evaluate_exterior_sign_reference_torch",
    "evaluate_global_coupler_family_reference_torch",
    "evaluate_global_coupler_reference_torch",
    "exterior_sign_vector_from_sparse_table",
    "evaluate_real_factorized_schedule_torch",
    "evaluate_young_yamanouchi_pair_cg_runtime_schedule",
    "format_block_trivial_lambda",
    "BasisLabel",
    "basis_label_from_compact",
    "basis_label_from_entry",
    "coerce_basis_label",
    "format_nu",
    "format_ye3t_basis",
    "format_ye3t_sector",
    "format_young_subgroup",
    "to_compact",
    "to_filename_safe",
    "to_human",
    "to_json",
    "to_latex",
    "fermion_wedge_physical_output_type",
    "fermion_wedge_sign_partition",
    "compile_fermion_wedge_ye3t_basis_inventory",
    "default_kappa_blocks_for_content",
    "exterior_tuples",
    "fermion_wedge_hidden_target_permutations",
    "generate_library_for_labels",
    "generate_real_factorized_coefficient_schedule_for_labels",
    "generate_torch_real_factorized_coefficient_schedule_for_labels",
    "generalized_sector_counts",
    "infer_repeated_channel_blocks",
    "integer_partitions",
    "local_coefficient_materialization_benchmark_table",
    "littlewood_richardson_chain_coefficient",
    "littlewood_richardson_chain_labels",
    "littlewood_richardson_coefficient",
    "littlewood_richardson_tableaux",
    "make_pattern_spec",
    "matrix_from_sparse_coefficient_table",
    "numeric_dense_from_sparse_coefficient_table",
    "pair_partition",
    "plan_ye3t_backend",
    "torch_dense_from_sparse_coefficient_table",
    "torch_exterior_sign_vector_from_sparse_table",
    "torch_sparse_coo_from_sparse_coefficient_table",
    "partition_centralizer_orbit_count",
    "permutation_irrep_for_character",
    "reduced_multiplicity_inner_product",
    "reduced_multiplicity_inner_product_native",
    "repeated_channel_reduction",
    "resolve_target_Ls",
    "selected_young_character_irreps_for_pattern",
    "set_partitions_of_size",
    "subduction_from_matrix_units",
    "specht_partition_family",
    "symmetric_group_character",
    "tensor_product_output_irreps",
    "trivial_symmetric_subduction_coefficients",
    "with_schedule_planning",
    "ye3t_channel_reduction",
    "ye3t_symbolic_summary",
    "validate_analytical_young_e3_sector_catalog",
    "validate_partition_centralizer",
    "validate_young_subgroup_specht_coupling",
    "validate_young_subgroup_specht_coupling_family",
    "validate_young_specht_basis_construction_plan",
    "validate_young_yamanouchi_cg_tree_schedule",
    "validate_young_yamanouchi_cg_runtime_schedule",
    "validate_young_resolved_primitive_quotient",
    "validate_coefficient_backend",
    "validate_fast_path_policy",
    "validate_rank_coupling_mode",
    "validate_runtime_status",
    "validate_sparse_coefficient_table",
    "validate_sparse_coefficient_table_numeric",
    "validate_tree_schedule",
    "validate_young_orthogonal_coupling",
    "validate_young_orthogonal_nary_subduction",
    "validate_young_orthogonal_nary_subduction_coherence",
    "validate_young_orthogonal_nary_subduction_coherence_up_to_rank",
    "validate_young_orthogonal_couplings_up_to_rank",
    "young_induced_multiplicity_by_character",
    "young_nary_induced_multiplicity_by_character",
    "young_orthogonal_induced_coupling",
    "young_orthogonal_nary_coherence_cases",
    "young_orthogonal_nary_subduction",
    "young_orthogonal_validation_cases",
    "young_product_paths",
    "YoungResolvedPrimitiveQuotientValidation",
    "young_resolved_primitive_quotient",
    "young_specht_basis_construction_plan",
    "young_subgroup_specht_coupling_multiplicity",
    "young_subgroup_permutations",
    "young_yamanouchi_cg_tree_schedule",
]
