
"""Public facade for the ye3t exact representation stack.

This module keeps exact representation, count, IR, and schedule symbols
available from one place while loading runtime/compiler/accelerator symbols
only when callers explicitly ask for them.
"""

from importlib import import_module

from .coefficient_benchmarks import (
    DEFAULT_LOCAL_COEFFICIENT_BENCHMARK_TARGET_SECONDS,
    local_coefficient_materialization_benchmark_table,
)
from .core import YE3TAPI, infer_repeated_channel_blocks, make_pattern_spec
from .core.e3 import (
    IrrepTerm,
    TensorProductReduction,
    YE3TChannelReduction,
    YE3TSymbolicSummary,
    cg_tensor_product_reduction,
    repeated_channel_reduction,
    tensor_product_output_irreps,
    ye3t_channel_reduction,
    ye3t_symbolic_summary,
)
from .core.product_engine import (
    ExactFeatureSpace,
    ExactProductColumnDescriptor,
    ExactProductExpansionEngine,
    IndependentDecomposableProductSubspace,
    PrimitiveQuotientSummary,
)
from .notation import (
    BasisLabel,
    basis_label_from_compact,
    basis_label_from_entry,
    coerce_basis_label,
    format_block_trivial_lambda,
    format_nu,
    format_ye3t_basis,
    format_ye3t_sector,
    format_young_subgroup,
    to_compact,
    to_filename_safe,
    to_human,
    to_json,
    to_latex,
)
from .core.basis.exhaustive_enumeration import enumerate_rank_labels, integer_partitions, pair_partition
from .fixed_content import (
    FixedContentDecomposition,
    FixedContentModule,
    FixedContentMultiplicityLabel,
    FixedContentSector,
    FixedContentSpec,
)
from .ir import E3OperatorIR, build_operator_ir, build_operator_irs, resolve_target_Ls
from .pure_couplers import compile_permutation_coupler, compile_rotation_coupler, compile_same_rank_kronecker
from .message_passing import (
    ApplyBalancedYE3TChannelLinearUpdate,
    ApplyBalancedYE3TChannelLinearReferenceMessageLayer,
    ApplyBalancedYE3TCoupledSectorPathAngularCoupledReferenceMessageUpdate,
    ApplyBalancedYE3TCoupledSectorPathAngularProductMerge,
    ApplyBalancedYE3TCoupledSectorPathCoupledReferenceMessageUpdate,
    ApplyBalancedYE3TCoupledSectorPathProductMerge,
    ApplyBalancedYE3TMessageSumAggregation,
    ApplyBalancedYE3TPairProductMerge,
    ApplyBalancedYE3TPathCoupledReferenceMessageUpdate,
    ApplyBalancedYE3TPairProductReferenceMessageLayer,
    ApplyBalancedYE3TRecursivePairProductReferenceStack,
    ApplyBalancedYE3TReferenceLinearReadout,
    ApplyBalancedYE3TReferenceMessageLayer,
    ApplyBalancedYE3TSectorwiseScalarUpdate,
    ValidateBalancedYE3TAtomicScalarReferenceReadout,
    ValidateBalancedYE3TAtomicScalarReferenceReadoutHiddenJacobian,
    ValidateBalancedYE3TFermionExchangeReferenceReadout,
    BalancedYE3TMessagePassingReferenceEvaluation,
    BalancedYE3TMessagePassingSchedule,
    BalancedYE3TMessageSectorReferenceEvaluation,
    BalancedYE3TMessageSectorSchedule,
    BalancedYE3TMessageStateReferenceView,
    BalancedYE3TMessageStateTensorContainer,
    BalancedYE3TCoupledSectorPathRecoupler,
    BalancedYE3TSchedule,
    BalancedYE3TChannelLinearReferenceMessageLayer,
    BalancedYE3TPathCoupledReferenceMessageUpdateLayer,
    BalancedYE3TReferenceMessageLayer,
    BalancedYE3TReferenceLinearReadoutEvaluation,
    BalancedYE3TRecursivePairProductReferenceStackEvaluation,
    BalancedYE3TRecursivePairProductReferenceStackLayer,
    BalancedYE3TRankCouplingPolicy,
    CompileBalancedYE3TCoupledSectorPathRecoupler,
    RankAdditiveInductionPath,
    RankGradedFeatureSpace,
    RankSector,
    CompileSameRankKroneckerRuntimeTables,
    SameRankKroneckerPath,
    SameRankKroneckerIntertwinerReferenceEvaluation,
    SameRankKroneckerIntertwinerReference,
    SameRankKroneckerMultiplicity,
    SameRankKroneckerReference,
    SameRankKroneckerRuntimeTableBundle,
    evaluate_same_rank_kronecker_intertwiner_reference_torch,
    CompileBalancedYE3TMessagePassingSchedule,
    EvaluateBalancedYE3TMessagePassingScheduleReference,
    PackageBalancedYE3TMessagePassingReferenceState,
)
from .spec import (
    BalancedYE3TMessageStateSpec,
    RANK_COUPLING_MODES,
    READOUT_AGGREGATIONS,
    STRICT_RUNTIME_STATUSES,
    YE3TBackendPlan,
    YE3TCouplerCertificate,
    YE3TReadoutSpec,
    YE3TRotationTarget,
    YE3TSpec,
    validate_coefficient_backend,
    validate_fast_path_policy,
    validate_rank_coupling_mode,
    validate_runtime_status,
    validate_tree_schedule,
)
from .global_coupler import (
    AngularCGMap,
    AssembleJointYoungE3Coupler,
    BalancedTreeCompilation,
    CompileBalancedTree,
    CompileExteriorPower,
    CompileGlobalYE3TCouplerFamily,
    CompileGlobalYE3TCouplers,
    CompileGlobalYE3TCouplersCached,
    assemble_joint_young_e3_coupler,
    CompileYE3TCouplers,
    CompileIndependentACE,
    ExteriorPowerSignTable,
    ExteriorSignReferenceEvaluation,
    GlobalCouplerFamilyReferenceEvaluation,
    GlobalCouplerReferenceEvaluation,
    GlobalYE3TCouplerFamily,
    GlobalYE3TLabel,
    JointYoungE3Coupler,
    RepeatedContentImageMap,
    YoungInductionCoupler,
    YoungSubductionMap,
    apply_exterior_sign_vector_torch,
    apply_sparse_coefficient_table_torch,
    compile_global_ye3t_coupler_family,
    compile_global_ye3t_couplers,
    compile_ye3t_couplers,
    evaluate_exterior_sign_reference_torch,
    evaluate_global_coupler_family_reference_torch,
    evaluate_global_coupler_reference_torch,
    exterior_sign_vector_from_sparse_table,
    matrix_from_sparse_coefficient_table,
    numeric_dense_from_sparse_coefficient_table,
    plan_ye3t_backend,
    torch_dense_from_sparse_coefficient_table,
    torch_exterior_sign_vector_from_sparse_table,
    torch_sparse_coo_from_sparse_coefficient_table,
    validate_sparse_coefficient_table,
    validate_sparse_coefficient_table_numeric,
)
from .representations.young_sectors import (
    YoungProductPath,
    YoungResolvedPrimitiveQuotient,
    YoungResolvedPrimitiveQuotientValidation,
    YoungSectorCounts,
    generalized_sector_counts,
    permutation_irrep_for_character,
    validate_young_resolved_primitive_quotient,
    young_product_paths,
    young_resolved_primitive_quotient,
)
from .representations.fixed_content_basis import YE3TFixedContentBasis
from .representations.young_orthogonal import (
    ReducedMultiplicityInnerProduct,
    YoungInducedBasisEntry,
    YoungOrthogonalCoupledVector,
    YoungOrthogonalCouplingTensor,
    YoungOrthogonalValidationReport,
    YoungOrthogonalValidationSuiteReport,
    reduced_multiplicity_inner_product,
    subduction_from_matrix_units,
    validate_young_orthogonal_coupling,
    validate_young_orthogonal_couplings_up_to_rank,
    young_induced_multiplicity_by_character,
    young_orthogonal_induced_coupling,
    young_orthogonal_validation_cases,
)
from .lowering.schedules import (
    ExactSchedule,
    FlatScheduleMetadata,
    MaterializationDecision,
    MaterializationPlan,
    ScheduleCostModel,
    ScheduleOptions,
    build_exact_schedule,
    build_flat_schedule_metadata,
    build_materialization_plan,
    with_schedule_planning,
)


_LAZY_EXPORTS = {
    "CompiledYE3TOperator": (".lowering.compiler", "CompiledYE3TOperator"),
    "MultiCompiledYE3TOperator": (".lowering.compiler", "MultiCompiledYE3TOperator"),
    "compile_ye3t_operator": (".lowering.compiler", "compile_ye3t_operator"),
    "compile_ye3t_operators": (".lowering.compiler", "compile_ye3t_operators"),
    "NativeRuntimePlan": (".runtime.native", "NativeRuntimePlan"),
    "NativeYE3TOperatorModule": (".runtime.native", "NativeYE3TOperatorModule"),
    "MultiNativeYE3TOperatorModule": (".runtime.native", "MultiNativeYE3TOperatorModule"),
    "build_native_runtime_plan": (".runtime.native", "build_native_runtime_plan"),
    "GeneralizedExactRuntimeBlock": (".runtime.generalized", "GeneralizedExactRuntimeBlock"),
    "GeneralizedExactRuntimeIrreps": (".runtime.generalized", "GeneralizedExactRuntimeIrreps"),
    "GeneralizedFullTensorProduct": (".runtime.generalized", "GeneralizedFullTensorProduct"),
    "JointYoungCGTensorSchedule": (".runtime.generalized", "JointYoungCGTensorSchedule"),
    "JointYoungCGProduct": (".runtime.generalized", "JointYoungCGProduct"),
    "YoungE3TensorProduct": (".runtime.generalized", "YoungE3TensorProduct"),
    "SchurWeylGuidedTreeProduct": (".runtime.schur_weyl_tree", "SchurWeylGuidedTreeProduct"),
    "SchurWeylTreeNode": (".runtime.schur_weyl_tree", "SchurWeylTreeNode"),
    "compile_schur_weyl_guided_tree_product": (
        ".runtime.schur_weyl_tree",
        "compile_schur_weyl_guided_tree_product",
    ),
    "compile_schur_weyl_guided_tree_product_from_coupler": (
        ".runtime.schur_weyl_tree",
        "compile_schur_weyl_guided_tree_product_from_coupler",
    ),
    "RealFactorizedCoefficientSchedule": (".core.couplings", "RealFactorizedCoefficientSchedule"),
    "TorchRealFactorizedCoefficientSchedule": (".core.couplings", "TorchRealFactorizedCoefficientSchedule"),
    "evaluate_real_factorized_schedule_torch": (".core.couplings", "evaluate_real_factorized_schedule_torch"),
    "generate_real_factorized_coefficient_schedule_for_labels": (
        ".core.couplings",
        "generate_real_factorized_coefficient_schedule_for_labels",
    ),
    "generate_torch_real_factorized_coefficient_schedule_for_labels": (
        ".core.couplings",
        "generate_torch_real_factorized_coefficient_schedule_for_labels",
    ),
    "SymmetricSquarePairTable": (".runtime.symmetric_power", "SymmetricSquarePairTable"),
    "SymmetricPowerMonomialTable": (".runtime.symmetric_power", "SymmetricPowerMonomialTable"),
    "allowed_symmetric_square_outputs": (".runtime.symmetric_power", "allowed_symmetric_square_outputs"),
    "allowed_symmetric_power_outputs": (".runtime.symmetric_power", "allowed_symmetric_power_outputs"),
    "symmetric_power_output_multiplicity": (
        ".runtime.symmetric_power",
        "symmetric_power_output_multiplicity",
    ),
    "symmetric_square_pair_table": (".runtime.symmetric_power", "symmetric_square_pair_table"),
    "symmetric_power_monomial_table": (".runtime.symmetric_power", "symmetric_power_monomial_table"),
    "symmetric_power_monomials": (".runtime.symmetric_power", "symmetric_power_monomials"),
    "symmetric_square_reference_real_tesseral": (
        ".runtime.symmetric_power",
        "symmetric_square_reference_real_tesseral",
    ),
    "symmetric_square_kernel_real_tesseral": (
        ".runtime.symmetric_power",
        "symmetric_square_kernel_real_tesseral",
    ),
    "symmetric_power_reference_real_tesseral": (
        ".runtime.symmetric_power",
        "symmetric_power_reference_real_tesseral",
    ),
    "symmetric_power_kernel_real_tesseral": (
        ".runtime.symmetric_power",
        "symmetric_power_kernel_real_tesseral",
    ),
    "symmetric_power_product_evaluator_real_tesseral": (
        ".runtime.symmetric_power",
        "symmetric_power_product_evaluator_real_tesseral",
    ),
    "symmetric_power_product_plan_contraction": (
        ".runtime.symmetric_power",
        "symmetric_power_product_plan_contraction",
    ),
    "symmetric_power_product_plan_batched_adjoint": (
        ".runtime.symmetric_power",
        "symmetric_power_product_plan_batched_adjoint",
    ),
    "symmetric_power_real_tesseral": (".runtime.symmetric_power", "symmetric_power_real_tesseral"),
    "symmetric_power_outputs_real_tesseral": (
        ".runtime.symmetric_power",
        "symmetric_power_outputs_real_tesseral",
    ),
    "symmetric_square_real_tesseral": (".runtime.symmetric_power", "symmetric_square_real_tesseral"),
    "symmetric_square_all_real_tesseral": (".runtime.symmetric_power", "symmetric_square_all_real_tesseral"),
    "symmetric_square_channels_real_tesseral": (".runtime.symmetric_power", "symmetric_square_channels_real_tesseral"),
    "symmetric_cube_real_tesseral": (".runtime.symmetric_power", "symmetric_cube_real_tesseral"),
    "symmetric_fourth_power_real_tesseral": (
        ".runtime.symmetric_power",
        "symmetric_fourth_power_real_tesseral",
    ),
    "OpenEquivarianceAvailability": (".backends.openequivariance_bridge", "OpenEquivarianceAvailability"),
    "OpenEquivarianceBlockPlan": (".backends.openequivariance_bridge", "OpenEquivarianceBlockPlan"),
    "OpenEquivarianceLoweringPlan": (".backends.openequivariance_bridge", "OpenEquivarianceLoweringPlan"),
    "OpenEquivariancePairedCGSpec": (".backends.openequivariance_bridge", "OpenEquivariancePairedCGSpec"),
    "build_openequivariance_lowering_plan": (
        ".backends.openequivariance_bridge",
        "build_openequivariance_lowering_plan",
    ),
    "export_to_openequivariance_specs": (".backends.openequivariance_bridge", "export_to_openequivariance_specs"),
    "make_paired_uvu_spec": (".backends.openequivariance_bridge", "make_paired_uvu_spec"),
    "openequivariance_availability": (".backends.openequivariance_bridge", "openequivariance_availability"),
    "couple_packed_real_tesseral": (".paired_cg", "couple_packed_real_tesseral"),
    "normalize_packed_cg_backend": (".paired_cg", "normalize_packed_cg_backend"),
}


def __getattr__(name):
    """Load runtime or optional backend symbols on explicit access."""
    if name in _LAZY_EXPORTS:
        module_name, attr_name = _LAZY_EXPORTS[name]
        module = import_module(module_name, __package__)
        value = getattr(module, attr_name)
        globals()[name] = value
        return value
    raise AttributeError(name)


__all__ = [
    "YE3TAPI",
    "DEFAULT_LOCAL_COEFFICIENT_BENCHMARK_TARGET_SECONDS",
    "infer_repeated_channel_blocks",
    "local_coefficient_materialization_benchmark_table",
    "make_pattern_spec",
    "FixedContentDecomposition",
    "FixedContentModule",
    "FixedContentMultiplicityLabel",
    "FixedContentSector",
    "FixedContentSpec",
    "E3OperatorIR",
    "build_operator_ir",
    "build_operator_irs",
    "resolve_target_Ls",
    "ApplyBalancedYE3TChannelLinearUpdate",
    "ApplyBalancedYE3TChannelLinearReferenceMessageLayer",
    "ApplyBalancedYE3TCoupledSectorPathAngularCoupledReferenceMessageUpdate",
    "ApplyBalancedYE3TCoupledSectorPathAngularProductMerge",
    "ApplyBalancedYE3TCoupledSectorPathCoupledReferenceMessageUpdate",
    "ApplyBalancedYE3TCoupledSectorPathProductMerge",
    "ApplyBalancedYE3TMessageSumAggregation",
    "ApplyBalancedYE3TPairProductMerge",
    "ApplyBalancedYE3TPathCoupledReferenceMessageUpdate",
    "ApplyBalancedYE3TPairProductReferenceMessageLayer",
    "ApplyBalancedYE3TRecursivePairProductReferenceStack",
    "ApplyBalancedYE3TReferenceLinearReadout",
    "ApplyBalancedYE3TReferenceMessageLayer",
    "ApplyBalancedYE3TSectorwiseScalarUpdate",
    "ValidateBalancedYE3TAtomicScalarReferenceReadout",
    "ValidateBalancedYE3TAtomicScalarReferenceReadoutHiddenJacobian",
    "ValidateBalancedYE3TFermionExchangeReferenceReadout",
    "BalancedYE3TMessagePassingReferenceEvaluation",
    "BalancedYE3TMessagePassingSchedule",
    "BalancedYE3TMessageSectorReferenceEvaluation",
    "BalancedYE3TMessageSectorSchedule",
    "BalancedYE3TMessageStateReferenceView",
    "BalancedYE3TMessageStateTensorContainer",
    "BalancedYE3TCoupledSectorPathRecoupler",
    "BalancedYE3TSchedule",
    "BalancedYE3TChannelLinearReferenceMessageLayer",
    "BalancedYE3TPathCoupledReferenceMessageUpdateLayer",
    "BalancedYE3TReferenceMessageLayer",
    "BalancedYE3TReferenceLinearReadoutEvaluation",
    "BalancedYE3TRecursivePairProductReferenceStackEvaluation",
    "BalancedYE3TRecursivePairProductReferenceStackLayer",
    "BalancedYE3TRankCouplingPolicy",
    "CompileBalancedYE3TCoupledSectorPathRecoupler",
    "RankAdditiveInductionPath",
    "RankGradedFeatureSpace",
    "RankSector",
    "CompileSameRankKroneckerRuntimeTables",
    "SameRankKroneckerPath",
    "SameRankKroneckerIntertwinerReferenceEvaluation",
    "SameRankKroneckerIntertwinerReference",
    "SameRankKroneckerMultiplicity",
    "SameRankKroneckerReference",
    "SameRankKroneckerRuntimeTableBundle",
    "evaluate_same_rank_kronecker_intertwiner_reference_torch",
    "CompileBalancedYE3TMessagePassingSchedule",
    "EvaluateBalancedYE3TMessagePassingScheduleReference",
    "PackageBalancedYE3TMessagePassingReferenceState",
    "BalancedYE3TMessageStateSpec",
    "RANK_COUPLING_MODES",
    "READOUT_AGGREGATIONS",
    "STRICT_RUNTIME_STATUSES",
    "YE3TBackendPlan",
    "YE3TCouplerCertificate",
    "YE3TReadoutSpec",
    "YE3TRotationTarget",
    "YE3TSpec",
    "validate_coefficient_backend",
    "validate_fast_path_policy",
    "validate_rank_coupling_mode",
    "validate_runtime_status",
    "validate_tree_schedule",
    "AngularCGMap",
    "BalancedTreeCompilation",
    "CompileBalancedTree",
    "CompileExteriorPower",
    "CompileGlobalYE3TCouplerFamily",
    "CompileGlobalYE3TCouplers",
    "CompileGlobalYE3TCouplersCached",
    "AssembleJointYoungE3Coupler",
    "assemble_joint_young_e3_coupler",
    "CompileYE3TCouplers",
    "CompileIndependentACE",
    "ExteriorPowerSignTable",
    "ExteriorSignReferenceEvaluation",
    "GlobalCouplerFamilyReferenceEvaluation",
    "GlobalCouplerReferenceEvaluation",
    "GlobalYE3TCouplerFamily",
    "GlobalYE3TLabel",
    "JointYoungE3Coupler",
    "RepeatedContentImageMap",
    "YoungInductionCoupler",
    "YoungSubductionMap",
    "apply_exterior_sign_vector_torch",
    "apply_sparse_coefficient_table_torch",
    "compile_global_ye3t_coupler_family",
    "compile_global_ye3t_couplers",
    "compile_permutation_coupler",
    "compile_rotation_coupler",
    "compile_same_rank_kronecker",
    "compile_ye3t_couplers",
    "evaluate_exterior_sign_reference_torch",
    "evaluate_global_coupler_family_reference_torch",
    "evaluate_global_coupler_reference_torch",
    "exterior_sign_vector_from_sparse_table",
    "matrix_from_sparse_coefficient_table",
    "numeric_dense_from_sparse_coefficient_table",
    "plan_ye3t_backend",
    "torch_dense_from_sparse_coefficient_table",
    "torch_exterior_sign_vector_from_sparse_table",
    "torch_sparse_coo_from_sparse_coefficient_table",
    "validate_sparse_coefficient_table",
    "validate_sparse_coefficient_table_numeric",
    "ExactSchedule",
    "FlatScheduleMetadata",
    "MaterializationDecision",
    "MaterializationPlan",
    "ScheduleCostModel",
    "ScheduleOptions",
    "build_exact_schedule",
    "build_flat_schedule_metadata",
    "build_materialization_plan",
    "with_schedule_planning",
    "CompiledYE3TOperator",
    "MultiCompiledYE3TOperator",
    "compile_ye3t_operator",
    "compile_ye3t_operators",
    "NativeRuntimePlan",
    "NativeYE3TOperatorModule",
    "MultiNativeYE3TOperatorModule",
    "build_native_runtime_plan",
    "GeneralizedExactRuntimeBlock",
    "GeneralizedExactRuntimeIrreps",
    "GeneralizedFullTensorProduct",
    "JointYoungCGTensorSchedule",
    "JointYoungCGProduct",
    "YoungE3TensorProduct",
    "SchurWeylGuidedTreeProduct",
    "SchurWeylTreeNode",
    "compile_schur_weyl_guided_tree_product",
    "compile_schur_weyl_guided_tree_product_from_coupler",
    "RealFactorizedCoefficientSchedule",
    "TorchRealFactorizedCoefficientSchedule",
    "evaluate_real_factorized_schedule_torch",
    "generate_real_factorized_coefficient_schedule_for_labels",
    "generate_torch_real_factorized_coefficient_schedule_for_labels",
    "SymmetricSquarePairTable",
    "SymmetricPowerMonomialTable",
    "allowed_symmetric_square_outputs",
    "allowed_symmetric_power_outputs",
    "symmetric_power_output_multiplicity",
    "symmetric_square_pair_table",
    "symmetric_power_monomial_table",
    "symmetric_power_monomials",
    "symmetric_square_reference_real_tesseral",
    "symmetric_square_kernel_real_tesseral",
    "symmetric_power_reference_real_tesseral",
    "symmetric_power_kernel_real_tesseral",
    "symmetric_power_product_evaluator_real_tesseral",
    "symmetric_power_product_plan_batched_adjoint",
    "symmetric_power_product_plan_contraction",
    "symmetric_power_real_tesseral",
    "symmetric_power_outputs_real_tesseral",
    "symmetric_square_real_tesseral",
    "symmetric_square_all_real_tesseral",
    "symmetric_square_channels_real_tesseral",
    "symmetric_cube_real_tesseral",
    "symmetric_fourth_power_real_tesseral",
    "OpenEquivarianceAvailability",
    "OpenEquivarianceBlockPlan",
    "OpenEquivarianceLoweringPlan",
    "OpenEquivariancePairedCGSpec",
    "build_openequivariance_lowering_plan",
    "export_to_openequivariance_specs",
    "make_paired_uvu_spec",
    "openequivariance_availability",
    "couple_packed_real_tesseral",
    "normalize_packed_cg_backend",
    "IrrepTerm",
    "TensorProductReduction",
    "YE3TChannelReduction",
    "YE3TSymbolicSummary",
    "cg_tensor_product_reduction",
    "ye3t_channel_reduction",
    "ye3t_symbolic_summary",
    "repeated_channel_reduction",
    "tensor_product_output_irreps",
    "ExactFeatureSpace",
    "ExactProductColumnDescriptor",
    "ExactProductExpansionEngine",
    "format_block_trivial_lambda",
    "BasisLabel",
    "basis_label_from_compact",
    "basis_label_from_entry",
    "coerce_basis_label",
    "to_compact",
    "to_filename_safe",
    "to_human",
    "to_json",
    "to_latex",
    "format_ye3t_basis",
    "format_ye3t_sector",
    "format_nu",
    "format_young_subgroup",
    "IndependentDecomposableProductSubspace",
    "PrimitiveQuotientSummary",
    "enumerate_rank_labels",
    "integer_partitions",
    "pair_partition",
    "YoungProductPath",
    "YoungInducedBasisEntry",
    "ReducedMultiplicityInnerProduct",
    "YoungOrthogonalCoupledVector",
    "YoungOrthogonalCouplingTensor",
    "YoungOrthogonalValidationReport",
    "YoungOrthogonalValidationSuiteReport",
    "YoungResolvedPrimitiveQuotient",
    "YoungResolvedPrimitiveQuotientValidation",
    "YE3TFixedContentBasis",
    "YoungSectorCounts",
    "generalized_sector_counts",
    "permutation_irrep_for_character",
    "young_product_paths",
    "reduced_multiplicity_inner_product",
    "subduction_from_matrix_units",
    "validate_young_resolved_primitive_quotient",
    "validate_young_orthogonal_coupling",
    "validate_young_orthogonal_couplings_up_to_rank",
    "young_induced_multiplicity_by_character",
    "young_orthogonal_induced_coupling",
    "young_orthogonal_validation_cases",
    "young_resolved_primitive_quotient",
]
