
r"""Graded algebra / module utilities for exact ACE bases.

This submodule extends the fixed-rank exact ACE basis machinery into a *graded*
view.  The exact Schur--Weyl + Young-subgroup labeler already constructs, for a
fixed tensor-product degree ``N`` and target irrep ``L_R``, an exact basis of

.. math::

    \mathcal A_N^{(L_R)}.

The present file adds bookkeeping and conservative algorithms for assembling
those homogeneous sectors into a graded object

.. math::

    \mathcal A = \bigoplus_{N\ge 0}\bigoplus_{L_R\ge 0} \mathcal A_N^{(L_R)}.

For ``L_R = 0`` this is the invariant ring.  For general ``L_R`` it is a graded
module over that invariant ring.  The key practical consequence is that one can
speak not only about *linear* independence at fixed degree/rank, but also about
whether a basis function is generated by lower-degree products.

This implementation is intentionally modular:

``GradedBasisRegistry``
    Enumerates exact Schur--Weyl / Young-adapted homogeneous sectors.

``ExactSymbolicPrimitiveFilter``
    A conservative symbolic test that detects factorizations visible from the
    exact binary-tree labels without invoking any floating-point projection.

``SampledGeneratedSubspaceAnalyzer``
    A numerical add-on that estimates the span of lower-degree products by
    evaluating exact features on a set of probe structures and computing a rank
    revealing factorization.  This is not a substitute for a full exact product
    algebra, but it is useful for reconstruction / expressivity tests.

The comments below intentionally keep the mathematical connection explicit so
that this file can serve as both runtime code and theory-side documentation.
"""
from functools import lru_cache

import numpy as np

from ye3t.core.basis import YE3TBasisLabeler
from ye3t.core.basis.labels import LeafLabel, NodeLabel
from ye3t.core.basis.sector import ExactBasisSector
from ye3t.core.basis.validation import canonicalize_leaf_quantum_numbers, iter_canonical_leaf_labelings
from ye3t.core.labels import CompactLabel, normalize_compact_label
from ye3t._record import recordclass


@recordclass(('rank', 'L_R', 'labels', 'sector_data'), frozen = True)
class HomogeneousSector:
    r"""Exact homogeneous Schur--Weyl / Young-adapted sector.

    Parameters
    ----------
    rank
        Homogeneous tensor-product degree ``N``.
    L_R
        Target total angular momentum / output irrep.
    labels
        Canonical compact labels spanning ``\mathcal A_N^{(L_R)}``.

    Notes
    -----
    The sector is the finite-dimensional vector space

    .. math::

        \mathcal A_N^{(L_R)} = \mathrm{span}\{ B^{(L_R)}_{N,\alpha} \}_{\alpha=1}^{d_{N,L_R}},

    where the basis elements are produced by exact blockwise Schur--Weyl /
    Young-subgroup reduction followed by a canonical SO(3) coupling tree.
    """
    sector_data = None

    @property
    def dim(self):
        return len(self.labels)


@recordclass(('rank', 'L_R', 'all_labels', 'primitive_labels', 'decomposable_labels'), frozen = True)
class PrimitiveDecompositionSummary:
    r"""Summary of a graded primitive/decomposable split.

    ``decomposable_labels`` are basis elements flagged as lower-generated by the
    conservative symbolic filter.  ``primitive_labels`` are those that survive.

    For invariants, this corresponds to a conservative approximation to the
    quotient

    .. math::

        P_N^{(0)} \approx \mathcal A_N^{(0)} / D_N^{(0)},

    and for a fixed equivariant irrep ``L``

    .. math::

        P_N^{(L)} \approx \mathcal A_N^{(L)} / D_N^{(L)},
        \qquad
        D_N^{(L)} = \sum_{k=1}^{N-1} \mathcal A_k^{(0)}\,\mathcal A_{N-k}^{(L)}.

    The approximation comes from the fact that the present symbolic filter uses
    exact tree-visible factorization criteria rather than a full exact product
    expansion into the target homogeneous sector.
    """

    @property
    def primitive_dim(self):
        return len(self.primitive_labels)

    @property
    def decomposable_dim(self):
        return len(self.decomposable_labels)


class GradedBasisRegistry:
    r"""Registry of exact homogeneous sectors across rank and target irrep.

    The registry is the first ingredient needed for a graded algebra/module
    computation.  For each raw leaf multiset ``(n_1,l_1), \dots, (n_N,l_N)`` and
    target irrep ``L_R`` we construct the exact finite-dimensional homogeneous
    sector using ``ExactACELabeler``.  Caching turns this into a reusable lookup
    table for later primitive filtering, parameter counting, and numerical span
    tests.
    """

    def __init__(self, tree_type = "balanced"):
        self.tree_type = tree_type

    def sector_for_nl(self, nin, lin, L_R):
        canonical_nin, canonical_lin = canonicalize_leaf_quantum_numbers(nin, lin)
        return self._sector_for_canonical_nl(canonical_nin, canonical_lin, int(L_R))

    @lru_cache(maxsize=None)
    def _sector_for_canonical_nl(self, nin, lin, L_R):
        labeler = YE3TBasisLabeler(list(nin), list(lin), strict_target_validation=False, tree_type=self.tree_type)
        sector_data = labeler.sector_data_for_target(int(L_R))
        if sector_data is not None:
            labels = tuple(normalize_compact_label(entry.compact_label) for entry in sector_data.entries)
        else:
            labels = tuple(normalize_compact_label(x) for x in labeler.compact_labels_for_target(int(L_R)))
        return HomogeneousSector(rank=len(nin), L_R=int(L_R), labels=labels, sector_data=sector_data)

    def enumerate_degree_sector(
        self,
        *,
        rank,
        nmax,
        lmin,
        lmax,
        L_R,
    ):
        r"""Enumerate the union of all exact sectors for a descriptor degree.

        This corresponds to the finite direct sum over all leaf multisets

        .. math::

            \mathcal A_N^{(L_R)}(n_{\max}, l_{\min}, l_{\max})
            = \bigoplus_{\substack{1\le n_i\le n_{\max}\\ l_{\min}\le l_i\le l_{\max}}}
              \mathcal A_{(n_1,l_1),\dots,(n_N,l_N)}^{(L_R)}.
        """
        labels = []
        seen = set()
        for nin_shifted, lin_shifted in iter_canonical_leaf_labelings(
            rank,
            range(1, int(nmax) + 1),
            range(int(lmin), int(lmax) + 1),
        ):
            sec = self.sector_for_nl(nin_shifted, lin_shifted, int(L_R))
            for lab in sec.labels:
                if lab not in seen:
                    seen.add(lab)
                    labels.append(lab)
        labels.sort(key=lambda x: (x.rank, x.n_tuple, x.l_tuple, x.internal_Ls, x.tree_type, x.basis_key))
        return HomogeneousSector(rank=rank, L_R=int(L_R), labels=tuple(labels))

    def raw_tree_labels(self, nin, lin, L_R):
        """Return full tree labels, not only compact labels.

        These tree labels are the algebraic objects used by the conservative
        primitive filter.  They preserve exact left/right subtree structure and
        therefore let us test whether a descriptor visibly factors as a lower-
        degree invariant times another lower-degree invariant/equivariant.
        """
        canonical_nin, canonical_lin = canonicalize_leaf_quantum_numbers(nin, lin)
        return self._raw_tree_labels_for_canonical_nl(canonical_nin, canonical_lin, int(L_R))

    @lru_cache(maxsize=None)
    def _raw_tree_labels_for_canonical_nl(self, nin, lin, L_R):
        labeler = YE3TBasisLabeler(list(nin), list(lin), strict_target_validation=False, tree_type=self.tree_type)
        sector_data = labeler.sector_data_for_target(int(L_R))
        if sector_data is not None:
            return tuple(entry.structured_label for entry in sector_data.entries)
        return tuple(labeler.labels_for_target(int(L_R)))


class ExactSymbolicPrimitiveFilter:
    r"""Conservative symbolic primitive filter.

    This class implements an *exact label-side* approximation to the graded
    algebra/module quotient.  It never performs a Gram/SVD step and never asks a
    floating-point evaluator to project one basis onto another.  Instead, it uses
    the exact binary-tree labels produced by the Schur--Weyl + Young-subgroup
    backend and recursively checks whether a basis element has a visible product
    decomposition into lower-degree exact basis elements.

    Invariant mode
    --------------
    We mark ``b \in \mathcal A_N^{(0)}`` decomposable if some internal subtree
    split writes

    .. math::

        b = b_L\, b_R,
        \qquad
        b_L \in \mathcal A_k^{(0)},\;
        b_R \in \mathcal A_{N-k}^{(0)},

    with both factors recognized as exact lower-degree scalar basis elements.

    Equivariant module mode
    -----------------------
    For fixed output irrep ``L`` we mark ``b \in \mathcal A_N^{(L)}``
    decomposable if some split writes

    .. math::

        b = i\, e,
        \qquad
        i \in \mathcal A_k^{(0)},\;
        e \in \mathcal A_{N-k}^{(L)},

    again using exact lower-degree membership checks.

    This is conservative: descriptors that become lower-generated only after a
    nontrivial recoupling change of basis may survive.  That is precisely why the
    module is described as an *add-on* graded algebra layer rather than a claim
    of complete symbolic closure.
    """

    def __init__(self, registry = None):
        self.registry = registry or GradedBasisRegistry()

    @staticmethod
    def _to_compact(label_obj):
        return normalize_compact_label(label_obj.compact_label())

    def _subtree_product_candidates(self, label_obj):
        pairs = []

        def visit(node):
            if not isinstance(node, NodeLabel):
                return
            pairs.append((self._to_compact(node.left), self._to_compact(node.right)))
            visit(node.left)
            visit(node.right)

        visit(label_obj)
        return pairs

    @lru_cache(maxsize=None)
    def _compact_membership(self, label, L_R):
        sector = self.registry.sector_for_nl(tuple(label.n_tuple), tuple(label.l_tuple), int(L_R))
        return label in sector.labels

    def is_symbolically_decomposable(self, label_obj, mode = "invariant"):
        root = self._to_compact(label_obj)
        for left, right in self._subtree_product_candidates(label_obj):
            if mode == "invariant":
                if left.L_R == 0 and right.L_R == 0:
                    if self._compact_membership(left, 0) and self._compact_membership(right, 0):
                        if left.rank < root.rank and right.rank < root.rank:
                            return True
            elif mode == "equivariant_module":
                if left.L_R == 0 and right.L_R == root.L_R:
                    if self._compact_membership(left, 0) and self._compact_membership(right, root.L_R):
                        if left.rank < root.rank and right.rank < root.rank:
                            return True
                if right.L_R == 0 and left.L_R == root.L_R:
                    if self._compact_membership(right, 0) and self._compact_membership(left, root.L_R):
                        if left.rank < root.rank and right.rank < root.rank:
                            return True
            else:
                raise ValueError("mode must be 'invariant' or 'equivariant_module'")
        return False

    def primitive_summary_for_nl(self, nin, lin, L_R, mode = "invariant"):
        raw_labels = self.registry.raw_tree_labels(tuple(int(x) for x in nin), tuple(int(x) for x in lin), int(L_R))
        compact_labels = [self._to_compact(x) for x in raw_labels]
        primitive = []
        decomposable = []
        for raw, compact in zip(raw_labels, compact_labels):
            if self.is_symbolically_decomposable(raw, mode=mode):
                decomposable.append(compact)
            else:
                primitive.append(compact)
        return PrimitiveDecompositionSummary(
            rank=len(nin),
            L_R=int(L_R),
            all_labels=tuple(compact_labels),
            primitive_labels=tuple(primitive),
            decomposable_labels=tuple(decomposable),
        )


@recordclass(('full_dim', 'reduced_dim', 'rank_reduced', 'relative_reconstruction_error'), frozen = True)
class SampledSpanResult:
    r"""Numerical span / reconstruction report.

    This class supports the empirical statement that a primitive-aware reduced
    feature family retains expressivity.  Given a feature matrix ``X_full`` and a
    reduced matrix ``X_red`` sampled on a set of structures, we solve the least
    squares problem

    .. math::

        \min_W \| X_{\mathrm{red}} W - X_{\mathrm{full}} \|_F^2

    and report the relative Frobenius reconstruction error.
    """


class SampledGeneratedSubspaceAnalyzer:
    """Probe-structure analyzer for numerical graded-subspace tests.

    The exact symbolic layer above is rigorous but conservative.  This auxiliary
    class complements it with a numerical *expressivity* test.  It does not claim
    symbolic proof of generation, but it is useful for examples and regression
    tests that compare full and primitive-aware feature families.
    """

    @staticmethod
    def reconstruction_report(X_full, X_reduced, rcond = 1e-10):
        X_full = np.asarray(X_full, float)
        X_reduced = np.asarray(X_reduced, float)
        coef, *_ = np.linalg.lstsq(X_reduced, X_full, rcond=rcond)
        X_rec = X_reduced @ coef
        denom = np.linalg.norm(X_full)
        err = np.linalg.norm(X_rec - X_full) / max(denom, 1e-15)
        rank_red = int(np.linalg.matrix_rank(X_reduced, tol=rcond))
        return SampledSpanResult(
            full_dim=X_full.shape[1],
            reduced_dim=X_reduced.shape[1],
            rank_reduced=rank_red,
            relative_reconstruction_error=float(err),
        )
