import pytest


pytestmark = pytest.mark.fast


def test_ye3t_top_level_public_exports_are_classified():
    import ye3t

    representation_labels = {
        "AngularIrrep",
        "CoupledIrrepLabel",
        "GeneralizedSectorData",
        "Partition",
        "PermutationIrrep",
        "PermutationSubgroup",
        "PermutationSubgroupFactor",
        "YE3TRepresentation",
        "symmetric_group_character",
    }

    exact_basis_and_products = {
        "BasisLabel",
        "ExactFeatureSpace",
        "ExactProductColumnDescriptor",
        "ExactProductExpansionEngine",
        "FixedContentDecomposition",
        "FixedContentModule",
        "FixedContentMultiplicityLabel",
        "FixedContentSector",
        "FixedContentSpec",
        "IndependentDecomposableProductSubspace",
        "PrimitiveQuotientSummary",
        "build_invariant_sector_labels",
        "basis_label_from_compact",
        "basis_label_from_entry",
        "coerce_basis_label",
        "enumerate_rank_labels",
        "generate_library_for_labels",
        "integer_partitions",
        "pair_partition",
        "to_compact",
        "to_filename_safe",
        "to_human",
        "to_json",
        "to_latex",
    }

    angular_reductions = {
        "YE3TChannelReduction",
        "YE3TSymbolicSummary",
        "IrrepTerm",
        "TensorProductReduction",
        "cg_tensor_product_reduction",
        "repeated_channel_reduction",
        "tensor_product_output_irreps",
        "ye3t_channel_reduction",
        "ye3t_symbolic_summary",
    }

    ir_and_schedule = {
        "E3OperatorIR",
        "ExactSchedule",
        "FlatScheduleMetadata",
        "MaterializationDecision",
        "MaterializationPlan",
        "RealFactorizedCoefficientSchedule",
        "ScheduleCostModel",
        "ScheduleOptions",
        "TorchRealFactorizedCoefficientSchedule",
        "build_exact_schedule",
        "build_flat_schedule_metadata",
        "build_materialization_plan",
        "build_operator_ir",
        "build_operator_irs",
        "evaluate_real_factorized_schedule_torch",
        "generate_real_factorized_coefficient_schedule_for_labels",
        "generate_torch_real_factorized_coefficient_schedule_for_labels",
        "resolve_target_Ls",
        "with_schedule_planning",
    }

    young_sector_tools = {
        "YoungAnalyticalSectorCatalog",
        "YoungAnalyticalSectorCatalogValidation",
        "YoungAnalyticalSectorRecord",
        "YoungProductPath",
        "YoungResolvedPrimitiveQuotient",
        "YoungResolvedPrimitiveQuotientValidation",
        "YoungSectorCounts",
        "YoungSpechtBasisConstructionPlan",
        "YoungSpechtBasisConstructionPlanValidation",
        "YoungSpechtConstructionRecord",
        "YoungYamanouchiCGTreeSchedule",
        "YoungYamanouchiCGTreeScheduleValidation",
        "YoungYamanouchiCGRuntimeCoefficient",
        "YoungYamanouchiCGRuntimeSchedule",
        "YoungYamanouchiCGRuntimeScheduleValidation",
        "PartitionCentralizerValidationReport",
        "all_young_character_irreps_for_pattern",
        "analytical_young_e3_sector_catalog",
        "compile_young_specht_basis_schedule",
        "compile_young_yamanouchi_pair_cg_runtime_schedule",
        "dusson_barthelemy_trivial_sector_counts",
        "evaluate_young_yamanouchi_pair_cg_runtime_schedule",
        "generalized_sector_counts",
        "partition_centralizer_orbit_count",
        "permutation_irrep_for_character",
        "selected_young_character_irreps_for_pattern",
        "set_partitions_of_size",
        "specht_partition_family",
        "validate_analytical_young_e3_sector_catalog",
        "validate_partition_centralizer",
        "validate_young_specht_basis_construction_plan",
        "validate_young_yamanouchi_cg_tree_schedule",
        "validate_young_yamanouchi_cg_runtime_schedule",
        "validate_young_resolved_primitive_quotient",
        "young_yamanouchi_cg_tree_schedule",
        "young_product_paths",
        "young_resolved_primitive_quotient",
        "young_specht_basis_construction_plan",
    }

    young_orthogonal_tools = {
        "LittlewoodRichardsonChainLabel",
        "LittlewoodRichardsonTableau",
        "ReducedMultiplicityInnerProduct",
        "TrivialSymmetricSubductionCoefficients",
        "YoungInducedBasisEntry",
        "YoungNaryInducedBasisEntry",
        "YoungOrthogonalNaryCoherenceReport",
        "YoungOrthogonalNaryCoherenceSuiteReport",
        "YoungOrthogonalNarySubductionTensor",
        "YoungOrthogonalNaryValidationReport",
        "YoungOrthogonalCoupledVector",
        "YoungOrthogonalCouplingTensor",
        "YoungOrthogonalValidationReport",
        "YoungOrthogonalValidationSuiteReport",
        "YoungSubgroupSpechtCoupling",
        "YoungSubgroupSpechtCouplingSpec",
        "build_cached_young_subgroup_specht_coupling",
        "build_trivial_target_young_subgroup_specht_coupling",
        "build_young_subgroup_specht_coupling",
        "enumerate_young_subgroup_specht_couplings",
        "littlewood_richardson_chain_coefficient",
        "littlewood_richardson_chain_labels",
        "littlewood_richardson_coefficient",
        "littlewood_richardson_tableaux",
        "reduced_multiplicity_inner_product",
        "reduced_multiplicity_inner_product_native",
        "subduction_from_matrix_units",
        "trivial_symmetric_subduction_coefficients",
        "validate_young_orthogonal_coupling",
        "validate_young_orthogonal_nary_subduction",
        "validate_young_orthogonal_nary_subduction_coherence",
        "validate_young_orthogonal_nary_subduction_coherence_up_to_rank",
        "validate_young_orthogonal_couplings_up_to_rank",
        "validate_young_subgroup_specht_coupling",
        "validate_young_subgroup_specht_coupling_family",
        "young_induced_multiplicity_by_character",
        "young_nary_induced_multiplicity_by_character",
        "young_orthogonal_induced_coupling",
        "young_orthogonal_nary_coherence_cases",
        "young_orthogonal_nary_subduction",
        "young_orthogonal_validation_cases",
        "young_subgroup_specht_coupling_multiplicity",
        "young_subgroup_permutations",
    }

    public_facade_helpers = {
        "DEFAULT_LOCAL_COEFFICIENT_BENCHMARK_TARGET_SECONDS",
        "YE3TAPI",
        "format_block_trivial_lambda",
        "format_nu",
        "format_ye3t_basis",
        "format_ye3t_sector",
        "format_young_subgroup",
        "infer_repeated_channel_blocks",
        "local_coefficient_materialization_benchmark_table",
        "make_pattern_spec",
    }

    shared_spec_and_status = {
        "AngularCGMap",
        "ApplyBalancedYE3TChannelLinearUpdate",
        "ApplyBalancedYE3TChannelLinearReferenceMessageLayer",
        "ApplyBalancedYE3TCoupledSectorPathAngularCoupledReferenceMessageUpdate",
        "ApplyBalancedYE3TCoupledSectorPathAngularProductMerge",
        "ApplyBalancedYE3TCoupledSectorPathCoupledReferenceMessageUpdate",
        "ApplyBalancedYE3TCoupledSectorPathProductMerge",
        "ApplyBalancedYE3TMessageSumAggregation",
        "ApplyBalancedYE3TPairProductMerge",
        "ApplyBalancedYE3TPathCoupledReferenceMessageUpdate",
        "ApplyBalancedYE3TPairProductReferenceMessageLayer",
        "ApplyBalancedYE3TRecursivePairProductReferenceStack",
        "ApplyBalancedYE3TReferenceLinearReadout",
        "ApplyBalancedYE3TReferenceMessageLayer",
        "ApplyBalancedYE3TSectorwiseScalarUpdate",
        "ValidateBalancedYE3TAtomicScalarReferenceReadout",
        "ValidateBalancedYE3TAtomicScalarReferenceReadoutHiddenJacobian",
        "ValidateBalancedYE3TFermionExchangeReferenceReadout",
        "BalancedYE3TMessageStateSpec",
        "BalancedYE3TMessagePassingReferenceEvaluation",
        "BalancedYE3TMessagePassingSchedule",
        "BalancedYE3TMessageSectorReferenceEvaluation",
        "BalancedYE3TMessageSectorSchedule",
        "BalancedYE3TMessageStateReferenceView",
        "BalancedYE3TMessageStateTensorContainer",
        "BalancedYE3TChannelLinearReferenceMessageLayer",
        "BalancedYE3TCoupledSectorPathRecoupler",
        "BalancedYE3TPathCoupledReferenceMessageUpdateLayer",
        "BalancedYE3TReferenceMessageLayer",
        "BalancedYE3TReferenceLinearReadoutEvaluation",
        "BalancedYE3TRecursivePairProductReferenceStackEvaluation",
        "BalancedYE3TRecursivePairProductReferenceStackLayer",
        "BalancedYE3TRankCouplingPolicy",
        "BalancedTreeCompilation",
        "AssembleJointYoungE3Coupler",
        "CompileBalancedTree",
        "CompileBalancedYE3TMessagePassingSchedule",
        "CompileBalancedYE3TCoupledSectorPathRecoupler",
        "EvaluateBalancedYE3TMessagePassingScheduleReference",
        "PackageBalancedYE3TMessagePassingReferenceState",
        "CompileSameRankKroneckerRuntimeTables",
        "SameRankKroneckerIntertwinerReferenceEvaluation",
        "SameRankKroneckerIntertwinerReference",
        "SameRankKroneckerMultiplicity",
        "SameRankKroneckerReference",
        "SameRankKroneckerRuntimeTableBundle",
        "evaluate_same_rank_kronecker_intertwiner_reference_torch",
        "RANK_COUPLING_MODES",
        "CompileExteriorPower",
        "CompileGlobalYE3TCouplerFamily",
        "CompileGlobalYE3TCouplers",
        "CompileGlobalYE3TCouplersCached",
        "CompileYE3TCouplers",
        "assemble_joint_young_e3_coupler",
        "CompileIndependentACE",
        "ExteriorPowerSignTable",
        "ExteriorSignReferenceEvaluation",
        "FermionWedgeSectorSpec",
        "GlobalCouplerFamilyReferenceEvaluation",
        "GlobalCouplerReferenceEvaluation",
        "GlobalYE3TCouplerFamily",
        "GlobalYE3TLabel",
        "JointYoungE3Coupler",
        "KappaBlockLabel",
        "RepeatedContentImageMap",
        "READOUT_AGGREGATIONS",
        "STRICT_RUNTIME_STATUSES",
        "YE3TBackendPlan",
        "YE3TCouplerCertificate",
        "YE3TReadoutSpec",
        "YE3TRotationTarget",
        "YE3TSpec",
        "YoungInductionCoupler",
        "YoungSubductionMap",
        "apply_exterior_sign_vector_torch",
        "apply_sparse_coefficient_table_torch",
        "compile_global_ye3t_coupler_family",
        "compile_global_ye3t_couplers",
        "compile_permutation_coupler",
        "compile_rotation_coupler",
        "compile_same_rank_kronecker",
        "compile_fermion_wedge_ye3t_basis_inventory",
        "compile_ye3t_couplers",
        "default_kappa_blocks_for_content",
        "evaluate_exterior_sign_reference_torch",
        "evaluate_global_coupler_family_reference_torch",
        "evaluate_global_coupler_reference_torch",
        "exterior_sign_vector_from_sparse_table",
        "exterior_tuples",
        "fermion_wedge_hidden_target_permutations",
        "fermion_wedge_physical_output_type",
        "fermion_wedge_sign_partition",
        "matrix_from_sparse_coefficient_table",
        "numeric_dense_from_sparse_coefficient_table",
        "plan_ye3t_backend",
        "torch_dense_from_sparse_coefficient_table",
        "torch_exterior_sign_vector_from_sparse_table",
        "torch_sparse_coo_from_sparse_coefficient_table",
        "validate_coefficient_backend",
        "validate_fast_path_policy",
        "validate_rank_coupling_mode",
        "validate_runtime_status",
        "validate_sparse_coefficient_table",
        "validate_sparse_coefficient_table_numeric",
        "validate_tree_schedule",
    }

    groups = (
        representation_labels,
        exact_basis_and_products,
        angular_reductions,
        ir_and_schedule,
        young_sector_tools,
        young_orthogonal_tools,
        public_facade_helpers,
        shared_spec_and_status,
    )
    expected_public = set().union(*groups)
    public = set(ye3t.__all__)

    assert expected_public == public
    for index, group in enumerate(groups):
        others = set().union(*(other for j, other in enumerate(groups) if j != index))
        assert not (group & others)
    for name in public:
        assert hasattr(ye3t, name), name


def test_ye3t_public_surface_uses_canonical_names():
    import ye3t
    import ye3t.api as api

    old_names = {
        "GNE3API",
        "GNE3ChannelReduction",
        "GNE3SymbolicSummary",
        "gne3_channel_reduction",
        "gne3_symbolic_summary",
        "format_gne3_basis",
        "format_gne3_sector",
    }
    assert not (old_names & set(ye3t.__all__))
    assert not any(hasattr(ye3t, name) for name in old_names)
    assert "compile_gne3_operator" not in api.__all__
    assert "compile_gne3_operators" not in api.__all__
    assert "compile_schur_weyl_guided_tree_product_from_coupler" in api.__all__
    assert hasattr(api, "compile_schur_weyl_guided_tree_product_from_coupler")
    assert not hasattr(api, "compile_gne3_operator")
    assert not hasattr(api, "compile_gne3_operators")
    assert ye3t.YE3TAPI().summarize_ye3t((1, 1), (1, 1)).ye3t_symbolic is not None
