import json

from ye3t.multiplicity_tables import table_formatter_config_defaults, write_latex_table_from_config


def test_formatter_config_exposes_legacy_options():
    config = table_formatter_config_defaults()
    expected = {
        "input_format",
        "defaults",
        "layout",
        "caption",
        "label",
        "max_rows",
        "max_wide_columns",
        "wide_max_rank",
        "allow_huge_wide",
        "partition_style",
        "kappa_style",
        "lambda_style",
        "diagram_max_rank",
        "ydiagram_max_cells",
        "ydiagram_max_rows",
        "max_channel_blocks",
        "columns",
        "rank_placement",
        "group_placement",
        "context_header",
        "omit_N",
        "omit_group",
        "show_input_channels",
        "omit_nu",
        "omit_kappa",
        "omit_block_lambda",
        "omit_parent_lambda",
        "show_d_blocks",
        "show_cd",
        "count_codes",
        "count_scope",
        "count_symbol",
        "value_label",
        "profile_columns",
        "split_by_rank",
        "group_resolved_rows",
        "show_tags",
        "omit_tags",
        "row_colors",
        "no_row_colors",
        "ace_row_color",
        "sign_row_color",
        "mixed_row_color",
        "no_resizebox",
        "infer_trivial_labels",
        "no_auto_tags",
        "no_validate",
        "duplicate_policy",
        "normalized_out",
        "standalone_out",
        "print_layout",
    }
    assert expected <= set(config)
    assert {
        "N",
        "eta",
        "l",
        "nu",
        "kappa",
        "Lambda",
        "lambda",
        "profile_kind",
        "count_scope",
        "sector",
        "tags",
    } <= set(config["defaults"])


def test_write_latex_table_splits_rank_and_groups_resolved_rows(tmp_path):
    payload = {
        "schema": "ye3t-external-multiplicity-table-v2",
        "rows": [
            {
                "N": 2,
                "nu": [{"eta": 1, "l": 1, "count": 2}],
                "kappa": [[2]],
                "Lambda": [0],
                "lambda": "(2)",
                "c_kappa_lambda": 1,
                "d_kappa_Lambda": 1,
                "d_blocks": [1],
                "profile_kind": "M",
                "M_by_L": {"0": 1},
                "counts": {"YE3T": 1},
                "tags": "ACE;resolved_kappa_Lambda_multiplicity",
            },
            {
                "N": 2,
                "nu": [{"eta": 1, "l": 1, "count": 2}],
                "kappa": [[2]],
                "Lambda": [2],
                "lambda": "(2)",
                "c_kappa_lambda": 1,
                "d_kappa_Lambda": 1,
                "d_blocks": [1],
                "profile_kind": "M",
                "M_by_L": {"2": 1},
                "counts": {"YE3T": 1},
                "tags": "ACE;resolved_kappa_Lambda_multiplicity",
            },
            {
                "N": 3,
                "nu": [{"eta": 1, "l": 1, "count": 3}],
                "kappa": [[3]],
                "Lambda": [1],
                "lambda": "(3)",
                "c_kappa_lambda": 1,
                "d_kappa_Lambda": 1,
                "d_blocks": [1],
                "profile_kind": "M",
                "M_by_L": {"1": 1},
                "counts": {"YE3T": 1},
                "tags": "ACE;resolved_kappa_Lambda_multiplicity",
            },
        ],
    }
    input_json = tmp_path / "rows.json"
    output_tex = tmp_path / "table.tex"
    input_json.write_text(json.dumps(payload), encoding="utf-8")

    write_latex_table_from_config(
        input_json,
        output_tex,
        {
            "split_by_rank": True,
            "group_resolved_rows": True,
            "layout": "compact",
            "profile_columns": "omit",
            "count_codes": ["YE3T"],
            "columns": "full",
            "show_d_blocks": True,
        },
    )

    text = output_tex.read_text(encoding="utf-8")
    assert "% Generated by ye3t.multiplicity_tables" in text
    assert "Rank 2." in text
    assert "Rank 3." in text
    assert r"\multirow{2}{*}" in text
