"""Representation-facing structural labels for ye3t/SO(3) work."""

from importlib import import_module


_LAZY_MODULES = (
    "generalized_sector_data",
    "generalized_irreps",
    "partition_centralizer",
    "young_subgroup_specht_coupling",
    "projectors",
    "slot_groups",
    "su2",
    "tensor_products",
    "young_orthogonal",
    "young_yamanouchi_runtime",
    "young_sectors",
    "builder",
)


def __getattr__(name):
    for module_name in _LAZY_MODULES:
        module = import_module(f"{__name__}.{module_name}")
        if hasattr(module, name):
            value = getattr(module, name)
            globals()[name] = value
            return value
    raise AttributeError(name)


def __dir__():
    return sorted(set(globals()) | set(__all__))

__all__ = [
    "AngularIrrep",
    "CachedGeneralizedTensorProductComposer",
    "CouplingScheduleNode",
    "ComposedGeneralizedTensorProductBranch",
    "CoupledIrrepLabel",
    "ExactChangeOfGroupBasisBranch",
    "ExactChangeOfGroupBasisMap",
    "ExactLoweredChangeOfGroupBasisBranch",
    "ExactLoweredChangeOfGroupBasisMap",
    "ExactChangeOfGroupMap",
    "ExactChangeOfGroupSourcePair",
    "ExactSymbolicProjectorGeneralizedBasisBuilder",
    "ExactMergedTensorProductDecomposition",
    "ExactMergedTensorProductIntertwiner",
    "GeneralizedExactSymbolicLabeler",
    "GeneralizedSectorData",
    "GeneralizedIrrepWorkedExample",
    "GeneralizedTensorProductSchedule",
    "GeneralizedTensorProduct",
    "MergedPermutationIrrepTerm",
    "Partition",
    "PartitionCentralizerValidationReport",
    "YoungSubgroupSpechtCoupling",
    "YoungSubgroupSpechtCouplingSpec",
    "PermutationIrrep",
    "PermutationSubgroup",
    "PermutationSubgroupFactor",
    "SmallNProjectorGeneralizedBasisBuilder",
    "SmallNSymmetricGroupProjector",
    "SubgroupIsotypicProjector",
    "SubgroupMatrixUnit",
    "SpinSpatialSignSelection",
    "SU2CGEntry",
    "SU2CGMap",
    "SU2Irrep",
    "TreeAwareTensorProductRule",
    "ScheduledGeneralizedTensorProductResult",
    "LittlewoodRichardsonChainLabel",
    "LittlewoodRichardsonTableau",
    "ReducedMultiplicityInnerProduct",
    "TrivialSymmetricSubductionCoefficients",
    "YoungInducedBasisEntry",
    "YoungNaryInducedBasisEntry",
    "YoungOrthogonalNaryCoherenceReport",
    "YoungOrthogonalNaryCoherenceSuiteReport",
    "YoungOrthogonalNarySubductionTensor",
    "YoungOrthogonalNaryValidationReport",
    "YoungOrthogonalCoupledVector",
    "YoungOrthogonalCouplingTensor",
    "YoungOrthogonalValidationReport",
    "YoungOrthogonalValidationSuiteReport",
    "YoungAnalyticalSectorCatalog",
    "YoungAnalyticalSectorCatalogValidation",
    "YoungAnalyticalSectorRecord",
    "YoungProductPath",
    "YoungResolvedPrimitiveQuotient",
    "YoungResolvedPrimitiveQuotientValidation",
    "YoungSectorCounts",
    "YoungSpechtBasisConstructionPlan",
    "YoungSpechtBasisConstructionPlanValidation",
    "YoungSpechtConstructionRecord",
    "YoungYamanouchiCGTreeSchedule",
    "YoungYamanouchiCGTreeScheduleValidation",
    "YoungYamanouchiCGRuntimeCoefficient",
    "YoungYamanouchiCGRuntimeSchedule",
    "YoungYamanouchiCGRuntimeScheduleValidation",
    "adjacent_transposition",
    "adjacent_transposition_representation_matrix",
    "apply_slot_permutation",
    "all_young_character_irreps_for_pattern",
    "analytical_young_e3_sector_catalog",
    "build_balanced_pairwise_schedule",
    "build_exact_change_of_group_basis_map",
    "build_exact_change_of_group_map",
    "build_exact_lowered_change_of_group_basis_map",
    "build_trivial_target_young_subgroup_specht_coupling",
    "build_cached_young_subgroup_specht_coupling",
    "build_young_subgroup_specht_coupling",
    "build_tree_aware_generalized_tensor_product",
    "build_tree_aware_tensor_product_rule",
    "build_exact_merged_tensor_product_decomposition",
    "build_generalized_tensor_product_schedule",
    "combined_projector_matrix",
    "combined_projector_matrix_numeric",
    "compile_young_yamanouchi_pair_cg_runtime_schedule",
    "compile_young_specht_basis_schedule",
    "compose_permutations",
    "decorated_automorphism_group",
    "dusson_barthelemy_trivial_sector_counts",
    "evaluate_young_yamanouchi_pair_cg_runtime_schedule",
    "enumerate_young_subgroup_specht_couplings",
    "format_lowered_change_of_group_basis_map_report",
    "graph_template_automorphisms",
    "induced_factor_role_permutations",
    "lowered_change_of_group_basis_map_heatmap_data",
    "littlewood_richardson_coefficient",
    "littlewood_richardson_chain_coefficient",
    "littlewood_richardson_chain_labels",
    "littlewood_richardson_tableaux",
    "canonical_irrep_matrices",
    "canonical_irrep_matrices_native",
    "canonical_irrep_matrices_numeric",
    "build_invariant_sector_labels",
    "combined_projector_matrix_native",
    "generalized_sector_counts",
    "inverse_permutation",
    "mixed_symmetry_vector_cube_so3_gn_example",
    "build_left_schedule",
    "build_su2_cg_map",
    "permutation_cycle_type",
    "pair_orbits",
    "partition_centralizer_orbit_count",
    "permutation_irrep_for_character",
    "permute_state_slots",
    "projector_matrices_for_irrep",
    "projector_matrices_for_irrep_native",
    "projector_matrices_for_irrep_numeric",
    "projector_matrix_for_factor",
    "projector_matrix_for_factor_native",
    "projector_matrix_for_factor_numeric",
    "reduced_multiplicity_inner_product",
    "reduced_multiplicity_inner_product_native",
    "lowered_change_of_group_basis_map_report",
    "plot_lowered_change_of_group_basis_map_heatmaps",
    "restrict_merged_permutation_irrep_to_children",
    "repeated_channel_group",
    "rooted_typed_graph_automorphisms",
    "rooted_typed_star_automorphism_generators",
    "rooted_typed_tree_automorphism_generators",
    "rim_hook_removals",
    "standard_tableaux",
    "subduction_from_matrix_units",
    "subgroup_isotypic_projector",
    "subgroup_isotypic_projector_native",
    "subgroup_isotypic_projector_numeric",
    "subgroup_matrix_units_for_factor",
    "subgroup_matrix_units_for_factor_native",
    "subgroup_matrix_units_for_factor_numeric",
    "su2_clebsch_gordan",
    "su2_tensor_product_js",
    "spin_spatial_sign_selection",
    "set_partitions_of_size",
    "symmetric_square_vector_so3_gn_example",
    "symmetric_group_character",
    "selected_young_character_irreps_for_pattern",
    "slot_orbits",
    "specht_partition_family",
    "tableau_positions",
    "trivial_symmetric_subduction_coefficients",
    "merge_permutation_irrep_sequence",
    "merged_permutation_irrep_product_terms",
    "tree_aware_permutation_irrep_product",
    "tree_aware_tensor_product_output_labels",
    "validate_analytical_young_e3_sector_catalog",
    "validate_partition_centralizer",
    "validate_young_subgroup_specht_coupling",
    "validate_young_subgroup_specht_coupling_family",
    "validate_young_specht_basis_construction_plan",
    "validate_young_yamanouchi_cg_tree_schedule",
    "validate_young_yamanouchi_cg_runtime_schedule",
    "validate_young_resolved_primitive_quotient",
    "validate_young_orthogonal_coupling",
    "validate_young_orthogonal_nary_subduction",
    "validate_young_orthogonal_nary_subduction_coherence",
    "validate_young_orthogonal_nary_subduction_coherence_up_to_rank",
    "validate_young_orthogonal_couplings_up_to_rank",
    "young_induced_multiplicity_by_character",
    "young_nary_induced_multiplicity_by_character",
    "young_orthogonal_nary_coherence_cases",
    "young_orthogonal_nary_subduction",
    "young_orthogonal_induced_coupling",
    "young_orthogonal_validation_cases",
    "young_product_paths",
    "young_subgroup_specht_coupling_multiplicity",
    "young_resolved_primitive_quotient",
    "young_specht_basis_construction_plan",
    "young_subgroup_permutations",
    "young_yamanouchi_cg_tree_schedule",
]
